Pss 33
Bochesan/memory.game.yandex-praktikum pull request #17
Opened 2024-05-25 13:25 UTC by sayonar2k

### Какую задачу решаем
Сделал модалки (3 штуки) + базовый компонент, который можно переиспользовать для других модалок, которые в будущем (возможно) будут созданы.

### Скриншоты/видяшка (если есть)
![image](https://github.com/Bochesan/memory.game.yandex-praktikum/assets/33577099/f5c06b99-26f5-41d3-842f-da1782cfa7ed)

![image](https://github.com/Bochesan/memory.game.yandex-praktikum/assets/33577099/e7d1242f-aa48-44ba-8799-dad141854f9b)

![image](https://github.com/Bochesan/memory.game.yandex-praktikum/assets/33577099/4c7e92df-9f1e-43d4-987b-3d7b23ac7d17)

### TBD (если есть)

2024-05-25 19:57 UTC, sanityFair approved these changes

2024-05-25 20:12 UTC, pokrov1991 approved these changes

2024-05-26 12:16 UTC, kate-lozovaya requested changes
Оставила несколько комментариев. В основном они относятся к типу модалки. Ответь на них и призывай меня к ревью

2024-05-26 12:16 UTC, kate-lozovaya commented on packages/client/src/shared/components/modal-comps/types.ts
> +  Lose,
[Исправление]
Для `enum` можно указывать текстовые значения. Сейчас в `css` значения записаны как числа, что ненадежно, потому что значения могут добавиться или поменяться местами.
Лучше записать как `Lose = 'lose'` и т д

2024-05-26 12:16 UTC, kate-lozovaya commented on packages/client/src/shared/components/modal-comps/modal.tsx
> +          <div className={`${cls['content']} ${cls[`content--${type}`]}`}>
[Исправление]
`type` здесь - неизвестная строка. То есть возможно такое, что тут будет какой-то неверный класс. Нужно сделать маппер из `TypeModal` в `string`?
```ts
const typeMapper: Record<TypeModal, string> = {
  [TypeModal.Lose]: cls['content--lose'],
  ...
}
```

2024-05-26 12:16 UTC, kate-lozovaya commented on packages/client/src/shared/components/modal-comps/modal.tsx
> +          <div className={`${cls['content']} ${cls[`content--${type}`]}`}>
[Вопрос]
А точно ли нельзя обойтись без типа модалки тут?  Было бы хорошо, если бы само модельное окно не зависело от контента, а тип бы относился только к `children`.

2024-05-26 12:16 UTC, kate-lozovaya commented on packages/client/src/shared/components/modal-comps/modal-result.tsx
> +          {type === TypeModal.Win ? 'Победа!' : 'Поражение!'}
[Вопрос - Предложение]
На `exit` тоже будет текст `Поражение` получается? Может тут сделать маппер из TypeModal в текст?

2024-05-26 12:16 UTC, kate-lozovaya commented on packages/client/src/shared/components/modal-comps/modal-exit.tsx
> +  onExit: (e?: MouseEvent<HTMLButtonElement>) => void
[Предложение]
Мне нравится оформлять типы для функций вот так ` onExit(e?: MouseEvent<HTMLButtonElement>): void`, потому что так в IDE у нее будет другая подсветка. Это помогает проще ориентироваться в пропсах и сразу видеть, что - переменная, а что - функция

2024-05-26 22:34 UTC, sayonar2k commented on packages/client/src/shared/components/modal-comps/modal-result.tsx
> +          {type === TypeModal.Win ? 'Победа!' : 'Поражение!'}
тут же type принимает только TypeModal.Win и TypeModall.Lose

2024-05-26 22:40 UTC, sayonar2k commented on packages/client/src/shared/components/modal-comps/modal.tsx
> +          <div className={`${cls['content']} ${cls[`content--${type}`]}`}>
> [Исправление] `type` здесь - неизвестная строка. То есть возможно такое, что тут будет какой-то неверный класс. Нужно сделать маппер из `TypeModal` в `string`?
> 
> ```ts
> const typeMapper: Record<TypeModal, string> = {
>   [TypeModal.Lose]: cls['content--lose'],
>   ...
> }
> ```

мне кажется это лишнее,  первый вариант же более лаконичен (и не нужны никакие мапы)

2024-05-26 22:42 UTC, sayonar2k commented on packages/client/src/shared/components/modal-comps/modal.tsx
> +          <div className={`${cls['content']} ${cls[`content--${type}`]}`}>
> [Вопрос] А точно ли нельзя обойтись без типа модалки тут? Было бы хорошо, если бы само модельное окно не зависело от контента, а тип бы относился только к `children`.

У нас все модалки будут иметь одинаковый контент, если рассматривать в контексте большого приложения, я бы согласился с Вами, но у нас все модалки имеют одинаковый контент, и в будущем будут тоже (не будет другого дизайна, все модалки будут схожими)

2024-05-27 07:43 UTC, kate-lozovaya commented on packages/client/src/shared/components/modal-comps/modal.tsx
> +          <div className={`${cls['content']} ${cls[`content--${type}`]}`}>
> мне кажется это лишнее, первый вариант же более лаконичен (и не нужны никакие мапы)

Первый вариант не надежен, потому что можно сделать опечатку в классах и не заметить это. Либо переименовать значение в enum, потому что поменяется смысл, но забыть поменять в css, потому что ни одна проверка не подсветится. От всех таких ошибок как раз и защищает маппер. Именно для учебного проекта, где известно, что новых модалок не появится, это допустимо, но для реального проекта, в котором все может меняться - нет. Советую в будущем использовать мапперы для сопоставления enum и класса

2024-05-27 07:45 UTC, kate-lozovaya approved these changes
Ответила на комментарий про маппер. Для учебного проекта, где нет изменений это не критично, но лучше все же использовать маппер, чтобы избежать ошибок) 
В остальном все ок, поставлю апрув

2024-05-27 18:44 UTC, merged