Feature/pss 59 - Audio Api
Bochesan/memory.game.yandex-praktikum pull request #51
Opened 2024-07-13 11:20 UTC by sayonar2k

### Какую задачу решаем
Добавили музыку на главной, также при окончании времени и выигрыше

### Скриншоты/видяшка (если есть)
![image](https://github.com/user-attachments/assets/3b0d8de4-37bd-4c65-a53c-d0666bf749ca)

![image](https://github.com/user-attachments/assets/56fc279b-403e-43d1-ac40-c0807a67bd08)

### TBD (если есть)

2024-07-13 11:33 UTC, sanityFair approved these changes

2024-07-13 11:33 UTC, sanityFair commented on packages/client/src/shared/hooks/useMusic.tsx
> +    const audio = new Audio()
Лучше вынести вне UseEffect. Лучше создать экземпляр Audio один раз и обновлять его свойства при изменении соответствующих пропсов.

2024-07-13 11:33 UTC, sanityFair commented on packages/client/src/shared/hooks/useMusic.tsx
> +  const onClickBtn = useCallback(() => {
Здесь нужен useCallback?

2024-07-13 12:32 UTC, sayonar2k commented on packages/client/src/shared/hooks/useMusic.tsx
> +  const onClickBtn = useCallback(() => {
так-то не нужен, но чтоб постоянно не пересоздавалась

2024-07-13 12:32 UTC, sayonar2k commented on packages/client/src/shared/hooks/useMusic.tsx
> +    const audio = new Audio()
просто audio меняться не будет, для каждого аудио свой хук вызываться будет, пропсы меняться у него не будут.

2024-07-13 22:26 UTC, IvanPeleshok requested changes
Добрый день

Отлично потрудились
Оставил пару маленьких комментов
Предлагаю ознакомиться и поправить

Хорошего дня :)

2024-07-13 22:26 UTC, IvanPeleshok commented on packages/client/src/pages/main-page/main-page.tsx
> +  const musicBtn = useMusic({ src: '/music/theme.mp3', loop: true, ui: true })
Предлагаю не сокращать наименование переменных `musicButton`
Код пишется для разработчиков и стоит избегать таких моментов, где могут быть вопросы и недопонимания (следуем лучшим практикам чистого кода)

2024-07-13 22:26 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useMusic.tsx
> +  const btnRef = useRef<HTMLButtonElement | null>(null)
buttonRef

2024-07-13 22:26 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useMusic.tsx
> +    audio.src = src
Возможно стоит убедиться, что `src` был передан, иначе реализовать ранний выход или выбросить исключение

2024-07-13 22:26 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useMusic.tsx
> +    if (ui || !conditional) return
```
if (
  ui 
  || !conditinal 
  || !audioRef.current?.HAVE_ENOUGH_DATA)
} {
  return
}
```
Вообще, писать в одну строку условие с выходом не очень хорошая практика, т.к мешает отладке и в девтулзах будет не так удобно

2024-07-13 22:26 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useMusic.tsx
> +    if (!audioRef.current?.HAVE_ENOUGH_DATA) return
Реализуем ранее

2024-07-13 22:26 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useMusic.tsx
> +    <button style={btnStyle} onClick={onClickBtn} ref={btnRef}>
buttonStyle / buttonRef

2024-07-14 06:31 UTC, sayonar2k commented on packages/client/src/shared/hooks/useMusic.tsx
> +    audio.src = src
src - обязательное поле, поэтому тс будет ругаться

2024-07-14 06:34 UTC, sayonar2k commented on packages/client/src/shared/hooks/useMusic.tsx
> +    if (ui || !conditional) return
мне не очень нравится множественные условия в одном if, поэтому для простого понимания пишу несколько if

2024-07-14 10:34 UTC, IvanPeleshok approved these changes
Всё замечательно
Поздравляю, апрув

2024-07-16 07:45 UTC, merged